### ISSUE TITLE
Please consider moving sidebar to the left for mobile, to be consistent with desktop

### ISSUE THREAD

**Issue by mariusa** [creativetimofficial/vue-paper-dashboard#21]
On mobile, the menu icon & sidebar are on the right.
On tablet/desktop, sidebar is on the left.

Please consider making them consistent, both on left.
(as part of Bootstrap 4 upgrade?)

Thanks Cristi!

**Comment by dannyrb** [comment]
@mariusa I'd actually argue that it be kept the same way, or at least configurable by the user? With most people being right handed, and with larger screens, having the nav be on the right makes it much easier to use one-handed.

**Comment by mariusa** [comment]
That makes sense. Some more questions to consider:
* Would people use just 1 hand when working in a dashboard? 
* Would same people use the dashboard on both desktop and mobile, and in that case, would familiarity of sidebar placement (left) worth more than a possible productivity gain (right) ?
* What patterns do big apps use, which would bring familiarity to users? eg Gmail (native app), Shopify have menus on the left. If right is more productive, why don't these apps change?
