### ISSUE TITLE
npm run build es6

### ISSUE THREAD

**Issue by xhijack** [creativetimofficial/vue-paper-dashboard#40]
Hi,

I have no issue when npm run dev, but when npm run build I got problem.

ERROR in static/js/app.4ce960db8a59a3e50003.js from UglifyJs
Unexpected token: punc ()) [./~/vue-loader/lib/template-compiler.js?id=data-v-d4e56386!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/UIComponents/Inputs/formGroupInput.vue:17,3][static/js/app.4ce960db8a59a3e50003.js:5005,34]

FYI: Some script I use es6

**Comment by cristijora** [comment]
From the error, it seems you have the old version of the dashboard. Most likely there is some error with the `formGroupInput` component. Can you please share the code for it as the new version has slightly different code for this component.
