### ISSUE TITLE
Using VPD inside an existing project

### ISSUE THREAD

**Issue by boriskogan81** [creativetimofficial/vue-paper-dashboard#41]
I've got an existing Vue project and would like to add Vue Paper Dashboard inside it. Is there any documentation available on how to do this?

**Comment by cristijora** [comment]
Hello @boriskogan81 That depends on your project architecture.
Depending on your use-case you need 
- Be able to compile `.vue` files
- `sass` support
- support es6 syntax and dynamic imports
- copy over the src folder in your project and have an `@` webpack alias setup pointing to the `src` folder

This project uses Vue CLI 3. If you have a project based on Vue CLI 3 then you could basically drop in the `src` folder and proceed from there on.
