### ISSUE TITLE
Transpile dependency in node_modules

### ISSUE THREAD

**Issue by stanleyck** [creativetimofficial/vue-paper-dashboard#42]
Hi, thanks for a great implementation of the dashboard. 

I want to make use of the vue2-datatable in the dashboard (https://github.com/OneWayTech/vue2-datatable), so I've installed it via npm, and imported it in main.js. However, I cannot get it to work within the dashboard because babel does not transpile the module. Please mark that the datatable component uses object spread operator (...). To enable transpiling of this operator, I've installed and added the plugin @babel/plugin-proposal-object-rest-spread to .babelrc config file. However, I still get an error during compilation where it is complaining that this plugin is missing. I'm suspecting that this is because babel does not transpile files in node_modules.

Is there anything special I need to configure to get babel to also transpile the datatabel dependency in node_modules? 

P.S. I've tried adding transpileDependencies option to vue.config.js, but it doesn't seem to help: 

Information about transpileDependencies: https://www.npmjs.com/package/@vue/cli-plugin-babel: 

> By default, babel-loader excludes files inside node_modules dependencies. If you wish to explicitly transpile a dependency module, you will need to add it to the transpileDependencies option in vue.config.js

**Comment by mnugter** [comment]
Bit late but I just ran into the same problem. 

You should add problematic packages in vue.config.js:

```
module.exports = {
  transpileDependencies: [
    'dependency',
  ],
};
```

Problems that might need fixing:

1. Babel 7 moved from .babelrc to babel.config.js. you should use the new format.
2. VueJS dropped mjs support for now (read that somewhere, not sure anymore where). If the dependency uses .mjs files you need to include the following in vue.config.js:

```
module.exports = {
  chainWebpack: (config) => {
    config.module.rule('js').test(/\.m?jsx?$/);
    config.resolve.extensions.prepend('.mjs');
  },
};
```

I hope this helps!

**Comment by mnugter** [comment]
I have a PR for the mjs extension:
https://github.com/vuejs/vue-cli/pull/3485

**Comment by mnugter** [comment]
The PR has been merged which removes the needed fix in bulletpoint 2!
