### ISSUE TITLE
Documentation / Repo for PRO version went away

### ISSUE THREAD

**Issue by mlumbroso** [creativetimofficial/vue-paper-dashboard#44]
Hi,

Repo and documentation for PRO version trigger a 404 (https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=Welcome&selectedStory=to%20Vue%20Paper%20Dashboard%20PRO&full=0&down=1&left=1&panelRight=1&downPanel=tuchk4%2Freadme%2Fpanel  )

Btw, I don't get why it's not included directly inside the source...
Please put back the documentation as soon as possible !

Thanks

**Comment by alexandru-paduraru** [comment]
@mlumbroso thank you for pointing out, we are doing some changes in our hosting for the live preview and documentation. Can you please let us know where you found that link?

In the meantime please check this: https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation.html?selectedKind=Welcome&selectedStory=to%20Vue%20Paper%20Dashboard%20PRO&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Best,
Alex

**Comment by mlumbroso** [comment]
Hey,
Thanks for the link !

Found the other one here : https://demos.creative-tim.com/vue-paper-dashboard-pro/#/admin/overview (documentation tab in the settings)

**Comment by dacoders77** [comment]
https://cristijora.github.io/paper-dashboard-pro/documentation.html

404
File not found

The site configured at this address does not contain the requested file.
