### ISSUE TITLE
Bootstrap is-valid and is-invalid class in form-control doesn't work

### ISSUE THREAD

**Issue by christhofer** [creativetimofficial/vue-paper-dashboard#52]
Bootstrap's `is-valid` and `is-invalid` class for form-control is being overrided.

If not using Vue-Paper's `border-input` class, the border is being set to none, which makes the `is-valid` and `is-invalid` border color not showing.
If using Vue-Paper's `border-input` class, the `is-valid` and` is-invalid` color is being overrided by `border: 1px solid #CCC5B9;`

**Comment by Christhofernatalius** [comment]
Oh, Vue-Paper has its own `has-error` and `has-success`. It is put on the parent of the `form-control`.

Maybe it needs to be shown in demo?
